# Generated by Django 5.0.4 on 2024-05-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='genNombre',
            new_name='nombre',
        ),
    ]
